import funciones

# == Variables globales =============================================
max_row_size = ...
max_col_size = ...
...

# == Funcion principal ==============================================
def main():
    # = Crear un tablero ==================================
    ...
    # = Inicializar el tablero ============================
    ...
    # = Preguntar posicion y valor para insertar ==========
    ...
    # = Comprovar si el valor es valido ===================
    ...
    # = Si no es valido mostrar mensaje de error ==========

# == Condicion para encender la funcion principal ===================
if __name__ == "__main__":
    main()